ALTER TABLE relays ADD COLUMN IF NOT EXISTS index_id TINYINT(4) NOT NULL DEFAULT '0' AFTER type;
ALTER TABLE relays ADD COLUMN IF NOT EXISTS pre_post TINYINT(1) NOT NULL DEFAULT '0' AFTER index_id;
ALTER TABLE relays ADD COLUMN IF NOT EXISTS show_it TINYINT(1) NOT NULL DEFAULT '0' AFTER pre_post;
ALTER TABLE relays ADD COLUMN IF NOT EXISTS message_in TINYINT(1) NOT NULL DEFAULT '0' AFTER show_it;
